import { createEnv } from '@t3-oss/env-core'
import { z } from 'zod'

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
    PORT: z.coerce.number().default(3000),
    MONGODB_URI: z.string().url().default('mongodb://localhost:27017/ytdt-claims-pipeline'),
    JWT_SECRET: z.string().min(1).default('your-secret-key'),
    PIPELINE_TIMEOUT_MINUTES: z.coerce.number().default(60),
    SKIP_VPN: z
      .string()
      .transform((val) => ['true', '1'].includes(val.toLowerCase()))
      .default('false'),
    FRONTEND_URL: z.string().url(),
    MYSQL_HOST: z.string().min(1),
    MYSQL_USER: z.string().min(1),
    MYSQL_PASSWORD: z.string().min(1),
    MYSQL_DATABASE: z.string().min(1),
    VPN_CONFIG_FILE: z.string().min(1),
    VPN_AUTH_FILE: z.string().optional(),
    EXPORT_FOLDER_NAME_FORMAT: z.string().default('yyyyMMddHHmmss'),
    GOOGLE_DRIVE_NAME: z.string().optional(),
    SLACK_CHANNEL: z.string().default('#ytdt-pipeline'),
    SLACK_BOT_TOKEN: z.string().optional(),
    SLACK_SIGNING_SECRET: z.string().optional(),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    GOOGLE_WORKSPACE_DOMAINS: z.string().min(1),
    BASE_URL: z.string().url(),
    ML_API_ENDPOINT: z.string().url().optional(),
    GOOGLE_REDIRECT_URI: z.string().url(),
    K_SERVICE: z.string().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    MONGODB_URI: process.env.MONGODB_URI,
    JWT_SECRET: process.env.JWT_SECRET,
    PIPELINE_TIMEOUT_MINUTES: process.env.PIPELINE_TIMEOUT_MINUTES,
    SKIP_VPN: process.env.SKIP_VPN,
    FRONTEND_URL: process.env.FRONTEND_URL,
    MYSQL_HOST: process.env.MYSQL_HOST,
    MYSQL_USER: process.env.MYSQL_USER,
    MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
    MYSQL_DATABASE: process.env.MYSQL_DATABASE,
    VPN_CONFIG_FILE: process.env.VPN_CONFIG_FILE,
    VPN_AUTH_FILE: process.env.VPN_AUTH_FILE,
    EXPORT_FOLDER_NAME_FORMAT: process.env.EXPORT_FOLDER_NAME_FORMAT,
    GOOGLE_DRIVE_NAME: process.env.GOOGLE_DRIVE_NAME,
    SLACK_CHANNEL: process.env.SLACK_CHANNEL,
    SLACK_BOT_TOKEN: process.env.SLACK_BOT_TOKEN,
    SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_WORKSPACE_DOMAINS: process.env.GOOGLE_WORKSPACE_DOMAINS,
    BASE_URL: process.env.BASE_URL,
    ML_API_ENDPOINT: process.env.ML_API_ENDPOINT,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
    K_SERVICE: process.env.K_SERVICE,
  },
  skipValidation: process.env.SKIP_ENV_VALIDATION === 'true',
})
